spring:
  servlet:
    multipart:
      max-file-size: 10GB # Max file size.
      max-request-size: 100GB # Max request size.
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_SCHEMA:seletivo}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      auto-commit: false
      connection-timeout: 250 # É uma configuração em milliseconds. O ideal é manter baixo para que estoure timeout logo e não prenda as threads.
      max-lifetime: 600000 # Tempo máximo que uma conexão pode ficar aberta (10 min) - security.
      maximum-pool-size: 20 # Mantemos até no máx 20 conexões com o banco de dados. O ideal é manter baixo mesmo, pois é algo custoso para o banco gerenciar. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      # Para aumentar a performance ao máximo, desabilitamos o auto-commit e o open-in-view.
      # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/

seletivo:
  swagger:
    url: http://localhost:8083
  s3:
    url: ${S3_URL:http://localhost:9000}
    urlPublic: ${S3_URL_PUBLIC:http://localhost:9003}
    access-key: ${S3_ACCESS_KEY:admin123}
    access-secret: ${S3_ACCESS_SECRET:strongpassword123}
    bucket-name: ${S3_BUCKET_NAME:fotos}
  user:
    username: admin
    password: password
  jwt:
    expiration-access-token: ${JWT_EXPIRATION_ACCES_TOKEN:30000000000}
    expiration-refresh-token:  ${JWT_EXPIRATION_REFRESH_TOKEN:86400000}

server:
  port: 8083
  servlet:
    context-path: /apiseletivo

storage:
  pessoa-foto:
    location-pattern: pessoaId-{pessoaId}

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

application:
  titulo: API Seletivo
  autor: Eduardo Roosevelt de Oliveira Silva
  minio: Console minio - http://localhost:9001
  swagger: Endereco do Swagger - http://localhost:8083/apiseletivo/swagger-ui/index.html#/